spring.application.name=forum-app
spring.profiles.active=dev

# Server
server.port=8081

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}
# OTP
otp.expiration-minutes=5